import { Capacitor } from '@capacitor/core';
import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import type { ExportRow } from './exportCsv';
import type { ForecastMonthDetail } from './forecast-export';

export interface ForecastRow {
  month: string;
  takeHome: number;
  totalExpenses: number;
  debtPayment: number;
  liquidCash: number;
  endingCash: number;
  netWorth: number;
  debtBalance: number;
  savingsBalance: number;
}

export interface DashboardSnapshot {
  month: string;
  liquidCash: number;
  netWorth: number;
  income: number;
  expenses: number;
  totalDebtPayments: number;
  savingsRate: number;
  totalSaved: number;
  ccDebt: number;
}

async function deliverHtml(html: string, filename: string, title: string): Promise<void> {
  if (Capacitor.isNativePlatform()) {
    const base64 = btoa(unescape(encodeURIComponent(html)));
    const result = await Filesystem.writeFile({
      path: filename,
      data: base64,
      directory: Directory.Cache,
    });
    await Share.share({
      title,
      url: result.uri,
      dialogTitle: `Export ${title}`,
    });
    return;
  }

  const win = window.open('', '_blank');
  if (!win) {
    alert('Allow pop-ups to export PDF, then try again.');
    return;
  }
  win.document.write(html);
  win.document.close();
  win.addEventListener('load', () => { win.focus(); win.print(); });
}

export async function exportTransactionsPdf(rows: ExportRow[], period = 'All Time'): Promise<void> {
  const exportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

  const htmlRows = rows.map(r => {
    const sign = r.type === 'income' ? '+' : '-';
    const amt = `${sign}$${Number(r.amount ?? 0).toFixed(2)}`;
    const cls = r.type === 'income' ? 'income' : 'expense';
    return `<tr>
      <td>${r.date ?? ''}</td>
      <td>${(r.note ?? '—').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</td>
      <td>${r.category ?? ''}</td>
      <td class="${cls}">${r.type ?? ''}</td>
      <td>${(r.payment_source ?? '—').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</td>
      <td class="amount ${cls}">${amt}</td>
    </tr>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Forgenta — Transactions</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; font-size: 11px; color: #111827; padding: 24px; }
    header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 16px; padding-bottom: 10px; border-bottom: 2px solid #111; }
    h1 { font-size: 15px; font-weight: 700; letter-spacing: -0.03em; }
    .meta { font-size: 10px; color: #6b7280; margin-top: 2px; }
    .right { text-align: right; }
    table { width: 100%; border-collapse: collapse; margin-top: 4px; }
    th { text-align: left; padding: 5px 6px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.07em; border-bottom: 1px solid #111; color: #374151; }
    th:last-child { text-align: right; }
    td { padding: 5px 6px; border-bottom: 1px solid #f3f4f6; vertical-align: middle; }
    .income { color: #16a34a; }
    .expense { color: #dc2626; }
    .amount { font-weight: 600; text-align: right; }
    tr:last-child td { border-bottom: none; }
    footer { margin-top: 16px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 9px; color: #9ca3af; }
    @media print { @page { margin: 1.5cm; size: A4 portrait; } body { padding: 0; } }
  </style>
</head>
<body>
  <header>
    <div>
      <h1>FORGENTA</h1>
      <p class="meta">Transactions &middot; ${period}</p>
    </div>
    <div class="right meta">
      <p>Exported ${exportDate}</p>
      <p>${rows.length} transaction${rows.length !== 1 ? 's' : ''}</p>
    </div>
  </header>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Note</th>
        <th>Category</th>
        <th>Type</th>
        <th>Source</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>${htmlRows}</tbody>
  </table>
  <footer>Generated by Forgenta &middot; getforgenta.com</footer>
</body>
</html>`;

  await deliverHtml(html, 'forgenta-transactions.html', 'Transactions PDF');
}

const PDF_STYLES = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, -apple-system, sans-serif; font-size: 9px; color: #111827; padding: 16px; }
  header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 10px; padding-bottom: 7px; border-bottom: 2px solid #111; }
  h1 { font-size: 13px; font-weight: 700; letter-spacing: -0.03em; }
  .meta { font-size: 9px; color: #6b7280; margin-top: 2px; }
  .right { text-align: right; }
  table { width: 100%; border-collapse: collapse; margin-top: 4px; }
  th { text-align: left; padding: 3px 5px; font-size: 7.5px; text-transform: uppercase; letter-spacing: 0.07em; border-bottom: 1px solid #111; color: #374151; }
  th:last-child, td:last-child { text-align: right; }
  td { padding: 3px 5px; border-bottom: 1px solid #f3f4f6; vertical-align: middle; font-size: 8.5px; }
  .pos { color: #16a34a; font-weight: 600; }
  .neg { color: #dc2626; font-weight: 600; }
  .num { text-align: right; }
  tr:last-child td { border-bottom: none; }
  .kpi-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin: 8px 0 12px; }
  .kpi { padding: 8px 10px; border: 1px solid #e5e7eb; border-radius: 6px; }
  .kpi-label { font-size: 8px; text-transform: uppercase; letter-spacing: 0.07em; color: #6b7280; }
  .kpi-value { font-size: 13px; font-weight: 700; margin-top: 2px; letter-spacing: -0.02em; }
  footer { margin-top: 10px; padding-top: 6px; border-top: 1px solid #e5e7eb; font-size: 8px; color: #9ca3af; }
  @media print { @page { margin: 0.8cm; size: A4 landscape; } body { padding: 0; } }

  .section-title { font-size: 11px; font-weight: 700; margin: 16px 0 6px; padding-top: 10px; border-top: 2px solid #111; }
  .month-block { border: 1px solid #e5e7eb; border-radius: 6px; padding: 8px 10px; margin-bottom: 8px; page-break-inside: avoid; }
  .month-head { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 6px; border-bottom: 1px solid #f3f4f6; padding-bottom: 4px; }
  .month-head h2 { font-size: 11px; font-weight: 700; }
  .month-head-figs { font-size: 8px; color: #374151; display: flex; gap: 12px; }
  .month-head-figs b { color: #111827; }
  .flow-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 6px; }
  .flow-col h3, .group-label { font-size: 7.5px; text-transform: uppercase; letter-spacing: 0.07em; color: #6b7280; margin-bottom: 2px; }
  .group-label { margin-top: 4px; }
  table.mini { width: 100%; border-collapse: collapse; }
  table.mini td { padding: 1.5px 4px; border-bottom: none; font-size: 8px; }
  table.mini td:last-child { text-align: right; white-space: nowrap; }
  table.mini tr.total td { font-weight: 700; border-top: 1px solid #d1d5db; padding-top: 2px; }
  .empty-line { color: #9ca3af; font-style: italic; }
`;

function fmt(n: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
}

function flowRowsHtml(items: { label: string; amount: number }[], sign: '+' | '−'): string {
  if (items.length === 0) return `<tr><td class="empty-line" colspan="2">None</td></tr>`;
  return items.map(it => `<tr><td>${it.label}</td><td>${sign}${fmt(it.amount)}</td></tr>`).join('');
}

function balanceRowsHtml(groups: { label: string; rows: { label: string; amount: number }[] }[]): string {
  const body = groups
    .filter(g => g.rows.length > 0)
    .map(g => `<tr><td class="group-label" colspan="2">${g.label}</td></tr>` + g.rows.map(r => `<tr><td>${r.label}</td><td>${fmt(r.amount)}</td></tr>`).join(''))
    .join('');
  return body || `<tr><td class="empty-line" colspan="2">None</td></tr>`;
}

function monthDetailHtml(d: ForecastMonthDetail): string {
  const transferRows = d.internalTransfers.length > 0
    ? `<div class="flow-col" style="margin-top:4px"><h3>Internal Transfers (no cash impact)</h3><table class="mini">${flowRowsHtml(d.internalTransfers, '+')}</table></div>`
    : '';
  return `<div class="month-block">
    <div class="month-head">
      <h2>${d.month}</h2>
      <div class="month-head-figs">
        <span>Start: <b>${fmt(d.startingCash)}</b></span>
        <span>End: <b>${fmt(d.endingCash)}</b></span>
        <span>Cash Floor: <b>${fmt(d.cashFloor)}</b></span>
        <span>Net Worth: <b>${fmt(d.netWorth)}</b></span>
      </div>
    </div>
    <div class="flow-grid">
      <div class="flow-col"><h3>Income</h3><table class="mini">${flowRowsHtml(d.income, '+')}</table></div>
      <div class="flow-col"><h3>Expenses</h3><table class="mini">${flowRowsHtml(d.expenses, '−')}</table></div>
    </div>
    ${transferRows}
    <div class="flow-grid">
      <div class="flow-col">
        <h3>Assets — Total ${fmt(d.totalAssets)}</h3>
        <table class="mini">${balanceRowsHtml([
          { label: 'Retirement', rows: d.retirementAccounts },
          { label: 'Investment', rows: d.investmentAccounts },
          { label: 'Savings', rows: d.savingsAccounts },
        ])}</table>
      </div>
      <div class="flow-col">
        <h3>Liabilities — Total ${fmt(d.totalLiabilities)}</h3>
        <table class="mini">${balanceRowsHtml([
          { label: 'Credit Cards', rows: d.creditCards },
          { label: 'Other Debt', rows: d.otherLiabilities },
          { label: 'Car Loans', rows: d.carLoans },
        ])}</table>
      </div>
    </div>
  </div>`;
}

export async function exportForecastPdf(rows: ForecastRow[], period = 'All Time', details: ForecastMonthDetail[] = []): Promise<void> {
  const exportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

  const htmlRows = rows.map(r => {
    const cashCls = r.endingCash < 0 ? 'neg' : '';
    const nwCls = r.netWorth < 0 ? 'neg' : 'pos';
    return `<tr>
      <td>${r.month}</td>
      <td class="num pos">${fmt(r.takeHome)}</td>
      <td class="num neg">−${fmt(r.totalExpenses)}</td>
      <td class="num neg">−${fmt(r.debtPayment)}</td>
      <td class="num ${cashCls}">${fmt(r.endingCash)}</td>
      <td class="num">${fmt(r.savingsBalance)}</td>
      <td class="num ${r.debtBalance > 0 ? 'neg' : ''}">${fmt(r.debtBalance)}</td>
      <td class="num ${nwCls}">${fmt(r.netWorth)}</td>
    </tr>`;
  }).join('');

  const detailSection = details.length > 0
    ? `<div class="section-title">Monthly Detail — Income, Expenses &amp; Account Balances</div>${details.map(monthDetailHtml).join('')}`
    : '';

  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Forgenta — Forecast</title><style>${PDF_STYLES}</style></head>
<body>
  <header>
    <div><h1>FORGENTA</h1><p class="meta">60-Month Forecast &middot; ${period}</p></div>
    <div class="right meta"><p>Exported ${exportDate}</p><p>${rows.length} month${rows.length !== 1 ? 's' : ''}</p></div>
  </header>
  <table>
    <thead><tr>
      <th>Month</th><th>Take-Home</th><th>Expenses</th><th>Debt Pmt</th><th>End Cash</th><th>Savings</th><th>Debt Bal</th><th>Net Worth</th>
    </tr></thead>
    <tbody>${htmlRows}</tbody>
  </table>
  ${detailSection}
  <footer>Generated by Forgenta &middot; getforgenta.com</footer>
</body></html>`;

  await deliverHtml(html, 'forgenta-forecast.html', 'Forecast PDF');
}

export async function exportDashboardPdf(snap: DashboardSnapshot): Promise<void> {
  const exportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });

  const kpis = [
    { label: 'Liquid Cash', value: fmt(snap.liquidCash) },
    { label: 'Net Worth', value: fmt(snap.netWorth) },
    { label: 'Monthly Income', value: fmt(snap.income) },
    { label: 'Monthly Expenses', value: fmt(snap.expenses) },
    { label: 'Debt Payments', value: fmt(snap.totalDebtPayments) },
    { label: 'Savings Rate', value: `${snap.savingsRate.toFixed(1)}%` },
    { label: 'Total Saved', value: fmt(snap.totalSaved) },
    { label: 'CC Debt', value: fmt(snap.ccDebt) },
    { label: 'Cash Flow', value: fmt(snap.income - snap.expenses - snap.totalDebtPayments) },
  ];

  const kpiHtml = kpis.map(k => `<div class="kpi"><div class="kpi-label">${k.label}</div><div class="kpi-value">${k.value}</div></div>`).join('');

  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Forgenta — Dashboard Snapshot</title><style>${PDF_STYLES}</style></head>
<body>
  <header>
    <div><h1>FORGENTA</h1><p class="meta">Command Center Snapshot &middot; ${snap.month}</p></div>
    <div class="right meta"><p>Exported ${exportDate}</p></div>
  </header>
  <div class="kpi-grid">${kpiHtml}</div>
  <footer>Generated by Forgenta &middot; getforgenta.com</footer>
</body></html>`;

  await deliverHtml(html, 'forgenta-dashboard.html', 'Dashboard PDF');
}
