import { useState } from 'react';
import { AlertTriangle, Trash2, X } from 'lucide-react';
import { formatCurrency } from '@/lib/calculations';
import { GENERATOR_LABEL, type DuplicateCollision } from '@/lib/duplicate-transaction-detection';

/**
 * "You typed this one, and the app also generates it."
 *
 * The panel that makes a double-charged month visible. Two actions, and deliberately only two:
 * delete the row the user typed, or say both are real and stop being asked. There is no "net them
 * out" and no automatic fix — see `duplicate-transaction-detection.ts` for why that is the whole
 * point.
 *
 * DELETE ASKS TWICE, and that is a considered departure from "fewer taps". Every other button in
 * this app is reversible; this one removes a financial record from a public-facing ledger with no
 * undo, and the panel appears next to rows the user may well have entered on purpose. The second
 * tap costs a moment; a mis-tap costs a row they have to reconstruct from memory. The confirm is
 * inline — no dialog, no navigation — so the fix still happens where the warning is, which is the
 * trip this feature exists to remove.
 */

interface DuplicateTransactionWarningProps {
  collisions: DuplicateCollision[];
  /** Delete the hand-entered row. Async so the caller can await its mutation. */
  onDelete: (manualId: string) => void | Promise<void>;
  /** Record "both of these are real" for this pair. */
  onDismiss: (key: string) => void;
  /** Rendered above the list. Defaults to the Transactions wording. */
  title?: string;
  className?: string;
}

const monthLabel = (monthKey: string): string => {
  const [year, month] = monthKey.split('-').map(Number);
  if (!Number.isFinite(year) || !Number.isFinite(month)) return monthKey;
  return new Date(year, month - 1, 1).toLocaleString('en-US', { month: 'long', year: 'numeric' });
};

export default function DuplicateTransactionWarning({
  collisions,
  onDelete,
  onDismiss,
  title = 'Possible duplicate payment',
  className = '',
}: DuplicateTransactionWarningProps) {
  // Which row is one tap from being deleted. Only ever one at a time — arming a second confirm
  // disarms the first, so a stray tap can never leave two loaded buttons on screen.
  const [confirmKey, setConfirmKey] = useState<string | null>(null);
  const [deletingKey, setDeletingKey] = useState<string | null>(null);

  if (collisions.length === 0) return null;

  const handleDelete = async (collision: DuplicateCollision) => {
    if (confirmKey !== collision.key) {
      setConfirmKey(collision.key);
      return;
    }
    setDeletingKey(collision.key);
    try {
      await onDelete(collision.manual.id);
    } finally {
      setDeletingKey(null);
      setConfirmKey(null);
    }
  };

  return (
    <div
      className={`border border-gold/40 bg-gold/10 p-3 sm:p-4 ${className}`}
      style={{ borderRadius: 'var(--radius)' }}
      role="alert"
    >
      <div className="flex items-start gap-2 mb-2">
        <AlertTriangle size={14} className="text-gold shrink-0 mt-0.5" />
        <div className="min-w-0">
          <p className="text-xs font-semibold text-gold">
            {title}
            {collisions.length > 1 ? ` — ${collisions.length} months` : ''}
          </p>
          <p className="text-[11px] text-muted-foreground mt-0.5">
            A transaction you entered by hand matches one this app already generates, so the month is
            counted twice. Delete the manual row if it was a copy — or keep both if you really paid
            twice.
          </p>
        </div>
      </div>

      <div className="space-y-2">
        {collisions.map(c => {
          const armed = confirmKey === c.key;
          const busy = deletingKey === c.key;
          return (
            <div
              key={c.key}
              className="bg-background/60 border border-border/60 px-2.5 py-2"
              style={{ borderRadius: 'var(--radius)' }}
            >
              <p className="text-xs font-medium">
                {monthLabel(c.monthKey)} · {formatCurrency(c.amount, true)} charged twice
              </p>
              <p className="text-[11px] text-muted-foreground mt-0.5 wrap-break-word">
                Your row: <span className="text-foreground">{c.manual.note || c.manual.category || 'Untitled'}</span> ({c.manual.date})
              </p>
              <p className="text-[11px] text-muted-foreground wrap-break-word">
                Generated by the {GENERATOR_LABEL[c.generated.kind]}: <span className="text-foreground">{c.generated.note || '—'}</span> ({c.generated.date})
              </p>
              <div className="flex items-center gap-2 mt-2">
                <button
                  type="button"
                  onClick={() => handleDelete(c)}
                  disabled={busy}
                  className={`text-[11px] font-semibold px-2 py-1 flex items-center gap-1 btn-press disabled:opacity-50 ${armed ? 'bg-destructive text-destructive-foreground' : 'bg-destructive/10 text-destructive border border-destructive/30'}`}
                  style={{ borderRadius: 'var(--radius)' }}
                >
                  <Trash2 size={11} />
                  {busy ? 'Deleting…' : armed ? 'Tap again to delete' : 'Delete my row'}
                </button>
                <button
                  type="button"
                  onClick={() => { setConfirmKey(null); onDismiss(c.key); }}
                  className="text-[11px] text-muted-foreground hover:text-foreground px-2 py-1 flex items-center gap-1 btn-press"
                  style={{ borderRadius: 'var(--radius)' }}
                >
                  <X size={11} />
                  Both are real
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
