import { describe, it, expect, vi, afterEach } from 'vitest';
import { simulateVariablePayoff, projectCardVariable, buildCardData, generateRecommendations, type CardData } from '../credit-card-engine';
import type { BalanceTranche } from '../balance-tranches';
import type { AccountRow } from '@/hooks/useSupabaseData';

// Golden tests for handoff item 3 — the engine's multi-rate (balance_tranches) integration.
//
// Every number below is hand-walked in the comment above the assertion, so a future change that
// moves one has to explain which step of the arithmetic it disagrees with. The engine's own
// long-standing rules (cash floor, look-ahead, month-0 sync, sub-dollar dust) are unchanged and
// covered by the rest of the suite; what these tests pin is:
//   1. PARITY  — a card with no tranches produces byte-identical numbers to the pre-tranche
//      engine. These values were generated by running the pre-change credit-card-engine.ts on
//      this exact fixture; they are not "whatever it does now".
//   2. per-tranche accrual and repricing at the promo cliff (Tre's real Discover).
//   3. avalanche ordering by MARGINAL rate, which a tranche can flip.
//   4. partial-ISB grace — the uncovered statement money accrues, not the whole balance.
//   5. sub-dollar residuals still zero out on a multi-rate card.

const CARD_BASE = {
  creditLimit: 10000, monthlyRepayments: 0, color: '#000',
  autopayFullBalance: false, statementBalancePhase: false, statementBalance: null,
  steadyMonthlyPurchases: 0, monthlyNewPurchases: 0, paymentPreference: null,
} as const;

function makeCard(overrides: Partial<CardData> & Pick<CardData, 'id'>): CardData {
  return {
    ...CARD_BASE, name: overrides.id, balance: 0, apr: 0,
    minPayment: 25, targetPayment: 25, dueDay: 15,
    ...overrides,
  } as CardData;
}

function tranche(overrides: Partial<BalanceTranche>): BalanceTranche {
  return { id: 't', label: 'Promo balance', balance: 0, apr: 0, promo_end_date: null, ...overrides };
}

// ─── 1. PARITY ────────────────────────────────────────────────────────────────────────────────

// Fixture deliberately mixes the paths that share code with the tranche walk: a plain revolving
// card, a cycling (paid-off) card that falls behind and builds backlog, and a card carrying a
// 0% installment plan — through a tight month that trips FLOOR_BREACHED / CARD_AT_RISK.
function parityCards(): CardData[] {
  return [
    makeCard({ id: 'A', name: 'Card A', balance: 4321.55, apr: 22.9, minPayment: 75, targetPayment: 75,
      monthlyNewPurchases: 210, dueDay: 12 }),
    makeCard({ id: 'C', name: 'Card C', balance: 0, apr: 26.99, monthlyNewPurchases: 350,
      paymentPreference: 'statement', dueDay: 5, autopayFullBalance: true }),
    makeCard({ id: 'D', name: 'Card D', balance: 3000, apr: 15.99, minPayment: 60, targetPayment: 60,
      dueDay: 28, installmentBalance: 1200, installmentMonthlyPayment: 100 }),
  ];
}

const PARITY_EVENTS = [
  { income: 3200, expenses: 2100 }, { income: 3200, expenses: 2400 },
  { income: 1200, expenses: 2600 }, { income: 3200, expenses: 2100 },
  { income: 3200, expenses: 2100 }, { income: 3200, expenses: 3000 },
  { income: 3200, expenses: 2100 }, { income: 3200, expenses: 2100 },
  { income: 3200, expenses: 2100 }, { income: 3200, expenses: 2100 },
  { income: 3200, expenses: 2100 }, { income: 3200, expenses: 2100 },
];

/** Captured from the PRE-TRANCHE engine (backups/2026-08-14_094540). Not one cent of this may move. */
const PARITY_GOLDEN = {
  payments: {
    A: [1663.03, 311.3, 75, 75, 75, 75, 76.13, 80.28, 352.69, 615.37, 615.62, 615.86],
    C: [0, 350, 50, 50, 68.96, 50.5, 824.85, 884.58, 612.42, 350, 350, 350],
    D: [136.97, 136.7, 136.43, 136.17, 135.91, 135.65, 135.4, 135.14, 134.89, 134.63, 134.38, 134.14],
  },
  balances: {
    A: [2740.99, 2692, 2878.37, 3068.3, 3261.85, 3459.1, 3658.98, 3858.53, 3789.47, 3456.42, 3116.76, 2770.38],
    C: [0, 0, 300, 606.75, 901.44, 1221.21, 773.83, 256.65, 0, 0, 0, 0],
    D: [2887.02, 2774.13, 2661.34, 2548.64, 2436.03, 2323.51, 2211.08, 2098.74, 1986.49, 1874.33, 1762.26, 1650.27],
  },
  interest: {
    A: [82.47, 52.31, 51.37, 54.93, 58.55, 62.25, 66.01, 69.83, 73.63, 72.32, 65.96, 59.48],
    C: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    D: [23.99, 23.81, 23.64, 23.47, 23.3, 23.13, 22.97, 22.8, 22.64, 22.47, 22.31, 22.15],
  },
  cyclingInterest: {
    A: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    C: [0, 0, 0, 6.75, 13.65, 20.27, 27.47, 17.4, 5.77, 0, 0, 0],
    D: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  cyclingOwed: {
    A: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    C: [0, 350, 350, 656.75, 970.4, 1271.71, 1598.68, 1141.23, 612.42, 350, 350, 350],
    D: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  backlog: {
    A: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    C: [0, 0, 300, 606.75, 901.44, 1221.21, 773.83, 256.65, 0, 0, 0, 0],
    D: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },
  mins: {
    A: [88.08, 55.87, 54.87, 58.67, 62.54, 66.48, 70.5, 74.58, 78.64, 77.24, 70.45, 63.52],
    C: [0, 0, 0, 25, 25, 25, 25, 25, 25, 0, 0, 0],
    D: [136.48, 136.22, 135.96, 135.7, 135.44, 135.18, 134.93, 134.68, 134.43, 134.18, 133.93, 133.69],
  },
  debtCash: {
    A: [1663.03, 311.3, 75, 75, 75, 75, 76.13, 80.28, 352.69, 615.37, 615.62, 615.86],
    C: [0, 0, 25, 25, 25, 25.5, 474.85, 534.58, 262.42, 0, 0, 0],
    D: [36.97, 36.7, 36.43, 36.17, 35.91, 35.65, 35.4, 35.14, 34.89, 34.63, 34.38, 34.14],
  },
  cash: [800, 802, -859.43, -20.6, 799.53, 738.38, 802, 802, 802, 802, 802, 802],
  payoff: 12,
  flagCount: 12,
};

describe('simulateVariablePayoff — no-tranche parity (the most important one)', () => {
  afterEach(() => vi.useRealTimers());

  it('reproduces the pre-tranche engine exactly for cards with no balance_tranches', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2026, 7, 14, 12, 0, 0));

    const sim = simulateVariablePayoff(parityCards(), 1500, 800, 'avalanche', 3000, 2200, 12, PARITY_EVENTS);

    for (const id of ['A', 'C', 'D'] as const) {
      expect(sim.monthlyPayments.get(id), `${id} payments`).toEqual(PARITY_GOLDEN.payments[id]);
      expect(sim.monthlyBalances.get(id), `${id} balances`).toEqual(PARITY_GOLDEN.balances[id]);
      expect(sim.monthlyInterest.get(id), `${id} interest`).toEqual(PARITY_GOLDEN.interest[id]);
      expect(sim.monthlyCyclingInterest.get(id), `${id} cycling interest`).toEqual(PARITY_GOLDEN.cyclingInterest[id]);
      expect(sim.monthlyCyclingOwed.get(id), `${id} cycling owed`).toEqual(PARITY_GOLDEN.cyclingOwed[id]);
      expect(sim.monthlyCyclingBacklog.get(id), `${id} backlog`).toEqual(PARITY_GOLDEN.backlog[id]);
      expect(sim.perCardMinPayments.get(id), `${id} minimums`).toEqual(PARITY_GOLDEN.mins[id]);
      expect(sim.monthlyDebtCashPayment.get(id), `${id} debt cash`).toEqual(PARITY_GOLDEN.debtCash[id]);
    }
    expect(sim.projectedCashByMonth).toEqual(PARITY_GOLDEN.cash);
    expect(sim.projectedPayoffMonths).toBe(PARITY_GOLDEN.payoff);
    // Same flags, same months, same cards at risk — the tight month still breaches identically.
    expect(sim.flags.length).toBe(PARITY_GOLDEN.flagCount);
    expect(sim.flags.filter(f => f.flag === 'CARD_AT_RISK').map(f => f.cardId).sort())
      .toEqual(['A', 'C', 'C', 'D', 'D', 'A'].sort());
  });

  it('treats an explicitly empty tranche list as no tranches at all', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2026, 7, 14, 12, 0, 0));
    const withEmpty = parityCards().map(c => ({ ...c, tranches: [] }));
    const sim = simulateVariablePayoff(withEmpty, 1500, 800, 'avalanche', 3000, 2200, 12, PARITY_EVENTS);
    expect(sim.monthlyInterest.get('A')).toEqual(PARITY_GOLDEN.interest.A);
    expect(sim.monthlyPayments.get('A')).toEqual(PARITY_GOLDEN.payments.A);
  });
});

// ─── 2. THE PROMO CLIFF ───────────────────────────────────────────────────────────────────────

/** Tre's real Discover: $5,037.73 at 7.99% until 2028-01-04 against a 16.6% standard rate. */
function discover(promoEnd: string | null): CardData {
  return makeCard({
    id: 'discover', name: 'Discover', balance: 10316.73, apr: 16.6,
    minPayment: 229, minPaymentIsManual: true, targetPayment: 229, dueDay: 1,
    tranches: [tranche({ id: 'bt', label: 'Balance transfer', balance: 5037.73, apr: 7.99, promo_end_date: promoEnd })],
  });
}

/** Minimum-only every month: the cap pins the cascade to exactly the $229 contract minimum. */
function runDiscover(card: CardData, months: number) {
  return simulateVariablePayoff(
    [card], 2000, 0, 'avalanche', 1500, 500, months,
    Array.from({ length: months }, () => ({ income: 1500, expenses: 500 })),
    undefined, undefined, undefined, undefined, undefined, undefined,
    Array.from({ length: months }, () => 229), // maxDebtPaymentByMonth
  );
}

describe('simulateVariablePayoff — per-tranche accrual and repricing at the promo cliff', () => {
  afterEach(() => vi.useRealTimers());

  it('shows the interest step in the month the promo expires (Discover, Jan 2028)', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2027, 10, 15, 12, 0, 0)); // Nov 15 2027 — m0=Nov, m1=Dec, m2=Jan 2028

    const sim = runDiscover(discover('2028-01-04'), 4);
    const interest = sim.monthlyInterest.get('discover')!;
    const balances = sim.monthlyBalances.get('discover')!;
    const payments = sim.monthlyPayments.get('discover')!;

    // Every month pays exactly the $229 contract minimum (manual ⇒ exact, and the cap holds the
    // cascade there), so the whole walk is determined by the interest split.
    expect(payments).toEqual([229, 229, 229, 229]);

    // m0 — Nov 2027, rates as of 2027-11-30, promo still live.
    //   tranche  5,037.73 × 7.99%/12 =  33.5428856
    //   remainder (10,316.73 − 5,037.73 = 5,279.00) × 16.6%/12 = 73.0261667
    //   total 106.5690523 → 106.57      (a single-APR card at 16.6% would charge 142.71 — below)
    //   end balance 10,316.73 + 106.57 − 229 = 10,194.30
    expect(interest[0]).toBe(106.57);
    expect(balances[0]).toBe(10194.30);

    // m1 — Dec 2027, rates as of 2027-12-31, promo STILL live (2027-12-31 < 2028-01-04).
    //   the tranche compounded at its own rate: 5,037.73 + 33.54 = 5,071.27
    //   tranche  5,071.27 × 7.99%/12 = 33.7662061
    //   remainder (10,194.30 − 5,071.27 = 5,123.03) × 16.6%/12 = 70.8685817
    //   total 104.6347878 → 104.63
    //   end balance 10,194.30 + 104.63 − 229 = 10,069.93
    expect(interest[1]).toBe(104.63);
    expect(balances[1]).toBe(10069.93);

    // m2 — Jan 2028, rates as of 2028-01-31 ≥ 2028-01-04 ⇒ THE TRANCHE REPRICES to 16.6%.
    //   tranche  (5,071.27 + 33.77 = 5,105.04) × 16.6%/12 = 70.6197200
    //   remainder (10,069.93 − 5,105.04 = 4,964.89) × 16.6%/12 = 68.6809783
    //   total 139.3006983 → 139.30 — a +$34.67 step against December, in the month it happens.
    expect(interest[2]).toBe(139.30);
    expect(Math.round((interest[2] - interest[1]) * 100) / 100).toBe(34.67);

    // m3 — Feb 2028: both buckets at 16.6% now, so the split is arithmetically the flat rate again.
    //   balance 10,069.93 + 139.30 − 229 = 9,980.23 → × 16.6%/12 = 138.0598483 → 138.06
    expect(balances[2]).toBe(9980.23);
    expect(interest[3]).toBe(138.06);

    // …and the step survives into the rendered projection rows (what Forecast/the debt table read),
    // not just the sim's internal series.
    const rows = projectCardVariable(
      discover('2028-01-04'), payments, 4, true, undefined,
      sim.monthlyRevolvingBalances.get('discover')!,
      sim.monthlyCyclingOwed.get('discover')!, sim.monthlyCyclingInterest.get('discover')!,
      balances, interest,
    ).months;
    expect(rows.map(r => r.interest)).toEqual([106.57, 104.63, 139.30, 138.06]);
    // (Feb's end balance: 9,980.23 + 138.06 − 229 = 9,889.29.)
    expect(rows.map(r => r.endBalance)).toEqual([10194.30, 10069.93, 9980.23, 9889.29]);
  });

  it('leaves the promo tranche untouched while the minimum is being paid (CARD Act §164)', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2027, 10, 15, 12, 0, 0));

    // The $229 goes to the 16.6% remainder, never the 7.99% tranche — which is exactly why the
    // tranche is still there at the cliff. If it were being paid down, m1's tranche interest would
    // be lower than m0's; instead it RISES (33.54 → 33.77) because it compounds untouched.
    const sim = runDiscover(discover('2028-01-04'), 2);
    const interest = sim.monthlyInterest.get('discover')!;
    // m1's total (104.63) minus the remainder's share on 5,123.03 (70.87) leaves the tranche's
    // 33.76 — a cent under its own 33.77 because the two sides round separately, and comfortably
    // above m0's 33.54, i.e. the tranche GREW rather than shrank.
    expect(Math.round((interest[1] - 70.87) * 100) / 100).toBe(33.76);
  });

  it('bites: with no promo_end_date the same card never steps up', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2027, 10, 15, 12, 0, 0));

    // Identical card, permanent 7.99% (promo_end_date null). The ledger walk through m0/m1 is
    // identical (same rates), so Jan 2028 isolates repricing alone:
    //   tranche 5,105.04 × 7.99%/12 = 33.9910580  (vs 70.6197200 repriced)
    //   remainder 4,964.89 × 16.6%/12 = 68.6809783
    //   total 102.6720363 → 102.67
    // Delete the cliff handling (trancheAprAsOf inside trancheInterestBreakdown) and the FIRST
    // test's m2 becomes this number — 102.67 instead of 139.30, $36.63/month understated forever.
    const sim = runDiscover(discover(null), 4);
    expect(sim.monthlyInterest.get('discover')![2]).toBe(102.67);
  });
});

// ─── 3. AVALANCHE ORDER FLIP ──────────────────────────────────────────────────────────────────

describe('simulateVariablePayoff — avalanche ranks on the MARGINAL rate', () => {
  afterEach(() => vi.useRealTimers());

  // LOW's stated APR (10%) sorts it behind MID (18%) under the single-APR model, but two thirds of
  // LOW's balance sits at 25.99% and that is where the next dollar lands (CARD Act §164). The
  // surplus therefore belongs to LOW.
  const lowTranche = tranche({ id: 'bt', label: 'Cash advance', balance: 4000, apr: 25.99 });
  const makePair = (withTranches: boolean): CardData[] => [
    makeCard({ id: 'LOW', name: 'Low stated APR', balance: 6000, apr: 10, minPayment: 100,
      minPaymentIsManual: true, targetPayment: 100, ...(withTranches ? { tranches: [lowTranche] } : {}) }),
    makeCard({ id: 'MID', name: 'Mid APR', balance: 6000, apr: 18, minPayment: 100,
      minPaymentIsManual: true, targetPayment: 100 }),
  ];
  const run = (cards: CardData[]) => simulateVariablePayoff(
    cards, 3000, 0, 'avalanche', 2000, 0, 2,
    [{ income: 2000, expenses: 0 }, { income: 2000, expenses: 0 }],
  );

  it('sends the surplus to the card carrying the expensive tranche', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2026, 7, 14, 12, 0, 0));

    // Pool: 3,000 cash + 2,000 income = 5,000 above a $0 floor. Minimums 100 + 100, surplus 4,800.
    const flipped = run(makePair(true));
    expect(flipped.monthlyPayments.get('LOW')![0]).toBe(4900);
    expect(flipped.monthlyPayments.get('MID')![0]).toBe(100);

    // Control: the SAME cards without the tranche sort the other way round, 18% before 10%.
    const control = run(makePair(false));
    expect(control.monthlyPayments.get('MID')![0]).toBe(4900);
    expect(control.monthlyPayments.get('LOW')![0]).toBe(100);

    // And the money lands where §164 says: m0 interest on LOW is
    //   4,000 × 25.99%/12 = 86.6333 + 2,000 × 10%/12 = 16.6667 → 103.30
    // (a single-APR read of the same card charges 6,000 × 10%/12 = 50.00 — the understatement).
    expect(flipped.monthlyInterest.get('LOW')![0]).toBe(103.30);
    expect(control.monthlyInterest.get('LOW')![0]).toBe(50);

    // The 4,900 clears the 25.99% bucket first (4,086.63 = 4,000 + its 86.63 of interest), leaving
    // 813.37 for the remainder, so month 1 accrues on the 10% money alone:
    //   end balance 6,000 + 103.30 − 4,900 = 1,203.30 → × 10%/12 = 10.0275 → 10.03
    expect(flipped.monthlyBalances.get('LOW')![0]).toBe(1203.30);
    expect(flipped.monthlyInterest.get('LOW')![1]).toBe(10.03);
  });
});

// ─── 4. PARTIAL-ISB GRACE ─────────────────────────────────────────────────────────────────────

describe('simulateVariablePayoff — partial-ISB grace accrues on the shortfall only', () => {
  afterEach(() => vi.useRealTimers());

  it('charges the uncovered statement money, not the whole balance', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2026, 7, 14, 12, 0, 0));

    // Prime Visa shape: a statement-preference card in grace whose available cash covers only part
    // of the statement. The cap holds every month's payment at exactly $1,000.
    const card = makeCard({
      id: 'prime', name: 'Prime Visa', balance: 3000, apr: 27.49, minPayment: 25, targetPayment: 25,
      monthlyNewPurchases: 500, paymentPreference: 'statement', statementBalancePhase: true, dueDay: 20,
    });
    const months = 3;
    const sim = simulateVariablePayoff(
      [card], 5000, 0, 'avalanche', 2000, 0, months,
      Array.from({ length: months }, () => ({ income: 2000, expenses: 0 })),
      undefined, undefined, undefined, undefined, undefined, undefined,
      Array.from({ length: months }, () => 1000),
    );
    const interest = sim.monthlyInterest.get('prime')!;
    const balances = sim.monthlyBalances.get('prime')!;

    expect(sim.monthlyPayments.get('prime')!.slice(0, 3)).toEqual([1000, 1000, 1000]);

    // m0 — in grace, nothing accrues (unchanged). Statement due 3,000, paid 1,000 ⇒ the card
    //      leaves grace carrying a 2,000 shortfall. End balance 2,000.
    expect(interest[0]).toBe(0);
    expect(balances[0]).toBe(2000);

    // m1 — only the shortfall accrues: 2,000 × 27.49%/12 = 45.8166 → 45.82. (Here the shortfall
    //      IS the whole balance, so the old grace-or-nothing model agrees.)
    //      Statement due 2,000 + 45.82 = 2,045.82, paid 1,000 ⇒ shortfall 1,045.82.
    //      End balance 2,000 + 45.82 + 500 purchases − 1,000 = 1,545.82.
    expect(interest[1]).toBe(45.82);
    expect(balances[1]).toBe(1545.82);

    // m2 — THE ONE THAT MOVES. Balance is 1,545.82 but only 1,045.82 of it is uncovered statement;
    //      the $500 of new purchases is still inside the grace period.
    //        1,045.82 × 27.49%/12 = 23.9580 → 23.96
    //      The old grace-or-nothing model charged the whole balance: 1,545.82 × 27.49%/12 = 35.41.
    //      Revert the partial model and this assertion reads 35.41 — that is the bite.
    expect(interest[2]).toBe(23.96);
    expect(interest[2]).toBeLessThan(35.41);
  });

  it('returns to full grace the moment a payment covers the statement', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2026, 7, 14, 12, 0, 0));

    const card = makeCard({
      id: 'prime', name: 'Prime Visa', balance: 3000, apr: 27.49, minPayment: 25, targetPayment: 25,
      monthlyNewPurchases: 500, paymentPreference: 'statement', statementBalancePhase: true, dueDay: 20,
    });
    // Month 0 underpays ($1,000 of a $3,000 statement); month 1 has enough to clear everything.
    const sim = simulateVariablePayoff(
      [card], 5000, 0, 'avalanche', 2000, 0, 4,
      Array.from({ length: 4 }, () => ({ income: 2000, expenses: 0 })),
      undefined, undefined, undefined, undefined, undefined, undefined,
      [1000, 99999, 99999, 99999],
    );
    const interest = sim.monthlyInterest.get('prime')!;
    expect(interest[1]).toBe(45.82);  // the shortfall month's charge
    // m1 pays the full 2,045.82 statement ⇒ grace is restored and nothing accrues afterwards.
    expect(interest[2]).toBe(0);
    expect(interest[3]).toBe(0);
  });
});

// ─── 5 & 6. DUST AND PLUMBING ─────────────────────────────────────────────────────────────────

describe('simulateVariablePayoff — multi-rate card, sub-dollar residual', () => {
  afterEach(() => vi.useRealTimers());

  it('still zeroes a sub-dollar remainder instead of leaving dust on a tranche card', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    vi.setSystemTime(new Date(2026, 7, 14, 12, 0, 0));

    // 1,200 balance, 600 of it at 6%, standard 12%.
    //   interest = 600 × 6%/12 (3.00) + 600 × 12%/12 (6.00) = 9.00 → owed 1,209.00
    // The cap pins the payment at 1,208.50, leaving $0.50 — which the engine's long-standing
    // dust rule must clear to exactly 0 rather than carry a multi-rate residue forever.
    const card = makeCard({
      id: 'dust', name: 'Dust', balance: 1200, apr: 12, minPayment: 25, targetPayment: 25,
      tranches: [tranche({ id: 'bt', balance: 600, apr: 6 })],
    });
    const sim = simulateVariablePayoff(
      [card], 5000, 0, 'avalanche', 0, 0, 2,
      [{ income: 0, expenses: 0 }, { income: 0, expenses: 0 }],
      undefined, undefined, undefined, undefined, undefined, undefined,
      [1208.50, 1208.50],
    );
    expect(sim.monthlyInterest.get('dust')![0]).toBe(9);
    expect(sim.monthlyPayments.get('dust')![0]).toBe(1208.50);
    expect(sim.monthlyBalances.get('dust')![0]).toBe(0);
    // …and the emptied ledger charges nothing the next month.
    expect(sim.monthlyBalances.get('dust')![1]).toBe(0);
    expect(sim.monthlyInterest.get('dust')![1]).toBe(0);
  });
});

describe('buildCardData — balance_tranches plumbing', () => {
  const account = (overrides: Partial<AccountRow>): AccountRow => ({
    id: 'card-1', user_id: 'test', name: 'Discover', account_type: 'credit_card', balance: 10316.73,
    credit_limit: 15000, apr: 16.6, payment_due_day: 1, active: true,
    min_payment: 229, payment_preference: null,
    ...overrides,
  });

  it('carries balance_tranches from the account row onto the card', () => {
    const cards = buildCardData([account({
      balance_tranches: [
        { id: 'bt', label: 'Balance transfer', balance: 5037.73, apr: 7.99, promo_end_date: '2028-01-04' },
      ],
    })], [], [], []);
    expect(cards[0].tranches).toEqual([
      { id: 'bt', label: 'Balance transfer', balance: 5037.73, apr: 7.99, promo_end_date: '2028-01-04', min_payment: null },
    ]);
  });

  it('gives a card with no (or unusable) balance_tranches an empty list, never undefined shapes', () => {
    expect(buildCardData([account({ balance_tranches: null })], [], [], [])[0].tranches).toEqual([]);
    expect(buildCardData([account({ balance_tranches: [{ balance: -5, apr: 3 }] })], [], [], [])[0].tranches).toEqual([]);
  });
});

describe('generateRecommendations — the avalanche label names the rate that ranked the card', () => {
  // X's standard APR (10%) is below Y's (20%), but X carries a 29.99% tranche, so its MARGINAL
  // rate ranks it first. The reason string must print that 29.99 — printing card.apr would show
  // a rate below the one that beat Y, which reads like the sort is broken.
  it('prints the marginal rate on a tranche card, card.apr on a plain one', () => {
    const cards = [
      makeCard({ id: 'X', name: 'Tranche card', balance: 6000, apr: 10,
        tranches: [tranche({ id: 'hi', label: 'Cash advance', balance: 5000, apr: 29.99 })] }),
      makeCard({ id: 'Y', name: 'Plain card', balance: 3000, apr: 20 }),
    ];
    const { recommendations } = generateRecommendations(cards, 10000, 0, 'avalanche', 0, 0);
    const x = recommendations.find(r => r.cardId === 'X')!;
    const y = recommendations.find(r => r.cardId === 'Y')!;
    expect(x.reason).toBe('Highest APR (29.99%)');
    expect(y.reason).toBe('Highest APR (20%)');
  });
});
